### ISSUE TITLE
[Adobe-Korea1-UCS2] 205A -> CDCDCDCD?

### ISSUE THREAD

**Issue by aminophen** [adobe-type-tools/mapping-resources-pdf#3]
In [Adobe-Korea1-UCS2 l.6132](https://github.com/adobe-type-tools/mapping-resources-pdf/blob/master/pdf2unicode/Adobe-Korea1-UCS2#L6132) I see

````
<205A> <CDCDCDCD>
````

but Adobe-Korea1 CID 8282 (two asterisks?) looks quite different from U+CDCD (췍).

**Comment by kenlunde** [comment]
Looking at similar glyphs, CID+8282 should map to U+FFFD, not the sequence <U+CDCD, U+CDCD>. I checked my data, and this error dates back about 15 years (2003).

**Comment by kenlunde** [comment]
Fixed just now.

**Comment by aminophen** [comment]
Isn't it better to map a sequence <U+002A, U+002A>?

**Comment by kenlunde** [comment]
In this case, no. This particular glyph is within a range of what I refer to as _junk_ glyphs that originated from Apple's extension to KS X 1001, and it's best not to do much with them. The fact that it took 15 years for this mapping issue to be found demonstrates that no one uses the glyphs in this range. In other words, when in doubt, it is best to map the glyphs in this region to U+FFFD.

**Comment by aminophen** [comment]
> This particular glyph is within a range of what I refer to as junk glyphs that originated from Apple's extension to KS X 1001

I didn't know that; thanks for the explanation!

**Comment by kenlunde** [comment]
Thank you for reporting this issue.
