### ISSUE TITLE
[Adobe-Japan1-UCS2] CID+580 should map to U+3058

### ISSUE THREAD

**Issue by r-seike** [adobe-type-tools/mapping-resources-pdf#5]
I suggest CID+580 and CID+9244 should map to U+3058 (じ) not U+3068 (と).

> <0244> <3068>

> <241c> <3068>

**Comment by kenlunde** [comment]
I corrected <0221> to be <0244> above, which is the hexadecimal value for CID+580.

**Comment by kenlunde** [comment]
Fixed just now in the 2019-04-01 release. Thank you for reporting.
