### ISSUE TITLE
[Adobe-Japan1-UCS2] CID10244..10262 circled number 32..50 (㉜..㊿)

### ISSUE THREAD

**Issue by t-tk** [adobe-type-tools/mapping-resources-pdf#7]
I suggest mapping of CID10244..10262 circled number 32..50 (㉜..㊿) to U+325C..32BF not to ASCII numbers.
Because U+325C..32BF are included in Unicode3.2 and JIS X 0213, I guess most of recent Japanese environment should support those code points.

**Comment by kenlunde** [comment]
The entire _Adobe-Japan1-UCS2_ ToUnicode mapping file needs to be revamped, and doing it piece-meal via multiple GitHub issues is an effective non-starter. If you're going to provide such feedback, which is welcomed, please do so via a consolidated issue, not multiple ones. In other words, close this issue, add its details to the one you opened a few minutes ago, then change its title to be more generic.

**Comment by t-tk** [comment]
OK. I will restart a new issue with more generic one.
