### ISSUE TITLE
[Adobe-Korea1-H-Mac] Duplicate lines

### ISSUE THREAD

**Issue by louisstuart96** [adobe-type-tools/mapping-resources-pdf#9]
So far, the following contents appear twice (lines 535-541 and lines 543-549) in `pdf2other/Adobe-Korea1-H-Mac`:
```
endcmap	
CMapName currentdict /CMap defineresource pop	
end	
end	

%%EndResource	
%%EOF	
```

Is this by-design or just an errorous copy of lines?

**Comment by punchcutter** [comment]
No special reason for those lines. I removed them.
